# **Lab: Engineering for ML**

## Exercise 2: EDA and Baseline Model

In this exercise we will start our data science project by preparing the dataset for modeling

**Pre-requisites:**
- Create a github account (https://github.com/join)
- Install git (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- Install pyenv (https://realpython.com/lessons/installing-pyenv/)
- Install poetry (https://python-poetry.org/docs/#installation)
- Install Wget for Windows users (https://eternallybored.org/misc/wget/)

The steps are:
1.   Setup Environment
2.   Load and explore dataset
3.   Prepare Data
4.   Split Dataset
5.   Get Baseline model
6.   Push changes

## 1. Setup Environment

**[1.1]** Download the dataset (https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36120-adv_mla/lab01/insurance.csv) into the sub-folder data/raw

In [ ]:
# For Windows users, you can download and install WGET. Or you can manually download the file from the link and save it to specified path
wget -P ~/Projects/adv_mla_2024/adv_mla_lab_1/data/raw https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36120-adv_mla/lab01/insurance.csv

**[1.5]** Launch Jupyter Lab from your virtual environment

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
#Solution:
poetry run jupyter lab

**[1.6]** Create a new Jupyter Notebook called `1_baseline.ipynb` inside the `work/adv_mla_lab_1/notebooks/` directory


## 2. Load and Explore Dataset

**[2.1]** Launch magic commands to automatically reload modules

In [1]:
%load_ext autoreload
%autoreload 2

**[2.2]** Import the pandas and numpy package

In [2]:
# Placeholder for student's code (Python code)

In [3]:
# Solution
import pandas as pd
import numpy as np

**[2.3]** Load the dataset into dataframe called df

In [4]:
# Placeholder for student's code (Python code)

In [5]:
#Solution:
df = pd.read_csv('../data/raw/insurance.csv')

**[2.4]** Display the first 5 rows of df

In [6]:
# Placeholder for student's code (Python code)

In [7]:
# Solution
df.head()

   age     sex     bmi  children smoker     region      charges
0   18  female  33.820         0     no  southeast   1630.66170
1   19  female  23.480         1     no  southeast   1836.80430
2   46    male  30.570         2     no  southeast   6632.35130
3   54    male  32.050         1    yes  southeast  31922.42950
4   21    male  21.345         4     no  northeast   1638.37255

**[2.5]** Display the dimensions (shape) of df

In [8]:
# Placeholder for student's code (Python code)

In [9]:
# Solution
df.shape

(50000, 7)

**[2.6]** Display the summary (info) of df

In [10]:
# Placeholder for student's code (Python code)

In [11]:
# Solution
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       50000 non-null  int64
 1   sex       50000 non-null  object
 2   bmi       50000 non-null  float64
 3   children  50000 non-null  int64
 4   smoker    50000 non-null  object
 5   region    50000 non-null  object
 6   charges   50000 non-null  float64
dtypes: float64(2), int64(2), object(3)
memory usage: 2.7+ MB

**[2.7]** Display the descriptive statistics of df

In [12]:
# Placeholder for student's code (Python code)

In [13]:
# Solution
df.describe(include='all')

,age,sex,bmi,children,smoker,region,charges
count,50000.000000,50000,50000.000000,50000.000000,50000,50000,50000.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,25176,NaN,NaN,38976,14197,NaN
mean,39.463120,NaN,30.713734,1.113760,NaN,NaN,13343.216363
std,14.117142,NaN,6.092727,1.212835,NaN,NaN,12131.222744
min,18.000000,NaN,17.291000,0.000000,NaN,NaN,1137.535900
25%,27.000000,NaN,26.600000,0.000000,NaN,NaN,4694.431800
50%,40.000000,NaN,30.300000,1.000000,NaN,NaN,9399.232775
75%,51.000000,NaN,34.570000,2.000000,NaN,NaN,17340.746925
max,64.000000,NaN,47.740000,5.000000,NaN,NaN,52589.810300

## 3. Prepare Data

**[3.1]** Create a copy of df and save it into a variable called df_cleaned

In [ ]:
# Placeholder for student's code (Python code)

In [14]:
# Solution
df_cleaned = df.copy()

**[3.2]** Extract the column `charges` and save it into variable called `target`

In [15]:
# Placeholder for student's code (Python code)

In [16]:
# Solution:
target = df_cleaned.pop('charges')

**[3.3]** Create 2 lists named `num_cols` and `cat_cols` containing respectively the names of numerical and categotical columns

In [17]:
# Placeholder for student's code (Python code)

In [18]:
# Solution:
num_cols = list(df_cleaned.select_dtypes('number').columns)
cat_cols = list(set(df_cleaned.columns) - set(num_cols))

**[3.4]** Import StandardScaler from sklearn.preprocessing

In [19]:
# Placeholder for student's code (Python code)

In [20]:
# Solution
from sklearn.preprocessing import StandardScaler, OneHotEncoder

**[3.5]** Instantiate the OneHotEncoder

In [21]:
# Placeholder for student's code (Python code)

In [22]:
# Solution
ohe = OneHotEncoder(sparse_output=False, drop='first')

**[3.6]** Fit and apply the OneHotEncoder on `df_cleaned` and save the result in `features`

In [23]:
# Placeholder for student's code (Python code)

In [24]:
# Solution
features = ohe.fit_transform(df_cleaned[cat_cols])

**[3.7]** Convert `features` into a dataframe

In [25]:
# Placeholder for student's code (Python code)

In [26]:
# Solution
features = pd.DataFrame(features, columns=ohe.get_feature_names_out())

**[3.8]** Instantiate the StandardScaler

In [27]:
# Placeholder for student's code (Python code)

In [28]:
# Solution
scaler = StandardScaler()

**[3.9]** Fit and apply the scaling on `df` and add the results into `features`

In [29]:
# Placeholder for student's code (Python code)

In [30]:
# Solution:
features[num_cols] = scaler.fit_transform(df_cleaned[num_cols])

**[3.10]** Import dump from joblib

In [31]:
# Placeholder for student's code (Python code)

In [32]:
# Solution:
from joblib import dump

**[3.11]** Save the one-hot encoder and scaler into the folder `models` and call the files respectively `ohe.joblib` and  `scaler.joblib`

In [33]:
# Placeholder for student's code (Python code)

In [34]:
# Solution:
dump(ohe, '../models/ohe.joblib')
dump(scaler, '../models/scaler.joblib')

['../models/scaler.joblib']

## 4. Split Dataset

**[4.1]** import train_test_split from sklearn.model_selection

In [35]:
# Placeholder for student's code (Python code)

In [36]:
# Solution
from sklearn.model_selection import train_test_split

**[4.2]** Split the data into training validation and testing sets as Numpy arrays

In [37]:
# Placeholder for student's code (Python code)

In [38]:
# Solution
X_data, X_test, y_data, y_test = train_test_split(features, target, test_size=0.2, random_state=8)
X_train, X_val, y_train, y_val = train_test_split(X_data, y_data, test_size=0.2, random_state=8)

**[4.3]** Print the dimensions of `X_train`, `X_val`, `X_test`

In [39]:
# Placeholder for student's code (Python code)

In [40]:
# Solution
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(32000, 8)
(8000, 8)
(10000, 8)

**[4.4]** Print the dimensions of `y_train`, `y_val`, `y_test`

In [41]:
# Placeholder for student's code (Python code)

In [42]:
# Solution
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(32000,)
(8000,)
(10000,)

**[4.5]** Save the sets into the folder `data/processed`

In [43]:
# Placeholder for student's code (Python code)

In [44]:
# Solution
X_train.to_csv('../data/processed/X_train.csv', index=False)
X_val.to_csv('../data/processed/X_val.csv', index=False)
X_test.to_csv('../data/processed/X_test.csv', index=False)
y_train.to_csv('../data/processed/y_train.csv', index=False)
y_val.to_csv('../data/processed/y_val.csv', index=False)
y_test.to_csv('../data/processed/y_test.csv', index=False)

## 5. Get Baseline Model

**[5.1]** Calculate the average of the target variable for the training set and save it into a variable called `pred_value`

In [45]:
# Placeholder for student's code (Python code)

In [46]:
# Solution:
pred_value = y_train.mean()

**[5.2]** Generate a numpy array with same dimensions as y_train that contains only the value saved in pred_value

In [47]:
# Placeholder for student's code (Python code)

In [48]:
# Solution:
y_base = np.full((len(y_train), 1), pred_value)

**[5.5]** Import mean_squared_error and mean_absolute_error from sklearn.metrics

In [49]:
# Placeholder for student's code (Python code)

In [50]:
# Solution:
from sklearn.metrics import root_mean_squared_error as rmse
from sklearn.metrics import mean_absolute_error as mae

**[5.6]** Display the RMSE and MAE scores of this baseline model on the training set

In [51]:
# Placeholder for student's code (Python code)

In [52]:
# Solution:
print(rmse(y_base, y_train))
print(mae(y_base, y_train))

12116.584822448176
9118.852804794265

## 6.   Push changes

**[6.1]** Add your changes to git staging area

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
# Solution:
git add .

**[6.2]** Create the snapshot of your repository and add a description

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
# Solution:
git commit -m "prepare data and baseline"

**[6.3]** Push your snapshot to Github

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
# Solution:
git push

**[6.4]** Stop Jupyter Lab